# Image Morphological Operations
- Erosion, Dilation, Opening, Closing
- Real examples: Noise removal, Object separation, Hole filling

In [1]:
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt
print('Morphological operations module loaded')

Morphological operations module loaded


## Binary Morphology
**Operates on**: Binary images (0 or 1)
**Structuring element**: Defines neighborhood
- Common: 3×3 square, disk, cross

**Basic operations**:
1. **Erosion**: Shrink objects, remove noise
2. **Dilation**: Grow objects, fill holes
3. **Opening**: Erosion + Dilation (remove small objects)
4. **Closing**: Dilation + Erosion (fill small holes)

In [2]:
# Create binary image with noise
np.random.seed(42)
img = np.zeros((200, 200), dtype=bool)
y, x = np.ogrid[:200, :200]
img[(y-100)**2 + (x-100)**2 < 40**2] = True

# Add noise (salt and pepper)
noise_coords = np.random.randint(0, 200, (100, 2))
for coord in noise_coords:
    img[coord[0], coord[1]] = not img[coord[0], coord[1]]

print('Binary image created with noise')
print(f'  Shape: {img.shape}')
print(f'  True pixels: {img.sum()}')

Binary image created with noise
  Shape: (200, 200)
  True pixels: 5093


## Erosion
Shrinks objects by removing boundary pixels
Removes small objects and noise

In [3]:
# Structuring element
struct = ndimage.generate_binary_structure(2, 1)  # Cross
print(f'Structuring element:\n{struct.astype(int)}')

# Erosion
eroded = ndimage.binary_erosion(img, structure=struct, iterations=2)
print(f'\nAfter erosion:')
print(f'  True pixels: {eroded.sum()} (reduced from {img.sum()})')

Structuring element:
[[0 1 0]
 [1 1 1]
 [0 1 0]]

After erosion:
  True pixels: 4454 (reduced from 5093)


## Dilation
Grows objects by adding boundary pixels
Fills small holes

In [4]:
# Dilation
dilated = ndimage.binary_dilation(img, structure=struct, iterations=2)
print(f'After dilation:')
print(f'  True pixels: {dilated.sum()} (increased from {img.sum()})')

After dilation:
  True pixels: 6590 (increased from 5093)


## Opening and Closing
**Opening** = Erosion → Dilation  
- Removes small objects  
- Smooths boundaries  

**Closing** = Dilation → Erosion  
- Fills small holes  
- Connects nearby objects

In [5]:
# Opening (remove noise)
opened = ndimage.binary_opening(img, structure=struct, iterations=2)
print('Opening: Removes small objects (noise)')

# Closing (fill holes)
closed = ndimage.binary_closing(img, structure=struct, iterations=2)
print('Closing: Fills small holes')

Opening: Removes small objects (noise)
Closing: Fills small holes


## Real Example: Fingerprint Enhancement
Improve ridge clarity using morphological operations

In [6]:
# Simulate fingerprint (ridges)
fingerprint = np.zeros((200, 200), dtype=bool)
for i in range(10, 190, 15):
    y = np.arange(200)
    x = i + 20*np.sin(y/20)
    x_int = x.astype(int)
    valid = (x_int >= 0) & (x_int < 200)
    for width in range(-2, 3):
        x_plot = np.clip(x_int + width, 0, 199)
        fingerprint[y[valid], x_plot[valid]] = True

# Add noise
fingerprint_noisy = fingerprint.copy()
noise = np.random.rand(200, 200) < 0.05
fingerprint_noisy ^= noise

print('Fingerprint enhancement:')
print('  1. Opening: Remove isolated noise')
print('  2. Closing: Connect broken ridges')

# Process
enhanced = ndimage.binary_opening(fingerprint_noisy, iterations=1)
enhanced = ndimage.binary_closing(enhanced, iterations=2)

print('  Result: Cleaner ridge structure')

Fingerprint enhancement:
  1. Opening: Remove isolated noise
  2. Closing: Connect broken ridges
  Result: Cleaner ridge structure


## Summary

### Morphological Operations:
```python
# Basic operations
eroded = ndimage.binary_erosion(img, structure, iterations)
dilated = ndimage.binary_dilation(img, structure, iterations)
opened = ndimage.binary_opening(img, structure, iterations)
closed = ndimage.binary_closing(img, structure, iterations)

# Structuring elements
struct_square = np.ones((3,3))
struct_cross = ndimage.generate_binary_structure(2, 1)
struct_disk = ndimage.generate_binary_structure(2, 2)
```

### When to Use:
- **Erosion**: Remove noise, shrink objects
- **Dilation**: Fill gaps, grow objects
- **Opening**: Remove small objects (noise filtering)
- **Closing**: Fill holes, connect components

### Applications:
✓ Noise removal (salt-and-pepper)  
✓ Object separation  
✓ Hole filling  
✓ Skeletonization  
✓ Fingerprint/document processing  