# Array Operations in NumPy
Three key concepts:
1. **Element-wise Arithmetic**: Operations applied to each element
2. **Broadcasting**: Operations between differently shaped arrays
3. **Comparison Operators**: Element-wise comparisons

All operations are vectorized (no loops needed)

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", a + b)        # [5,7,9]
print("Subtraction:", b - a)     # [3,3,3]
print("Multiplication:", a * b)  # [4,10,18]
print("Division:", b / a)        # [4.,2.5,2.]
print("Floor Division:", b // a) # [4,2,2]
print("Exponentiation:", a ** 2) # [1,4,9]
print("Modulus:", b % a)         # [0,1,]

# Scalar operations
print("\nScalar addition:", a + 10)  # [11,12,13]

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Floor Division: [4 2 2]
Exponentiation: [1 4 9]
Modulus: [0 1 0]

Scalar addition: [11 12 13]


### In-Place Operations
Modify arrays without creating copies using `+=`, `*=`, etc.

In [3]:
arr = np.array([1, 2, 3])
arr += 5
print("After +=5:", arr)  # [6,7,8]

arr *= 2
print("After *=2:", arr)  # [12,14,16]

# Works with arrays too
b = np.array([1, 1, 1])
arr -= b
print("After array subtraction:", arr)  # [11,13,15]

After +=5: [6 7 8]
After *=2: [12 14 16]
After array subtraction: [11 13 15]


## Broadcasting Rules
NumPy can operate on arrays with different shapes:
1. **Rule 1**: Pad smaller array with 1s on left  
   `(3,) → (1,3)`  
2. **Rule 2**: Stretch dimensions of size 1 to match  
   `(1,3) → (4,3)`  

**Valid if**:  
- Dimensions are equal, or  
- One dimension is 1  

Example:  
- (3,4) Array
- (1,4) Vector

- (3,4) Result

In [18]:

#Cell 6: Code - Broadcasting Examples**

# Vector + Scalar
vector = np.array([1, 2, 3])
print("Vector + 5:", vector + 5)  # [6,7,8]

# Matrix + Vector
matrix = np.array([[1,2,3], 
                   [4,5,6]])
print("\nMatrix + Vector:\n", matrix + vector) 
# [[2,4,6],
#  [5,7,9]]

# 3D + 2D
cube = np.ones((2,3,4))  # Shape (2,3,4)
print(f"This is cube \n {cube}")
matrix_2d = np.array([[1,2,3,4]])  # Shape (1,4)
print("\n3D + 2D:\n", (cube + matrix_2d))  # (2,3,4)

# Invalid broadcast
try:
    matrix + np.array([1,2])  # (2,3) + (2,) → incompatible
except ValueError as e:
    print("\nError:", e)

Vector + 5: [6 7 8]

Matrix + Vector:
 [[2 4 6]
 [5 7 9]]
This is cube 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3D + 2D:
 [[[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]

 [[2. 3. 4. 5.]
  [2. 3. 4. 5.]
  [2. 3. 4. 5.]]]

Error: operands could not be broadcast together with shapes (2,3) (2,) 


## Element-wise Comparisons
Return boolean arrays:  
- `==`, `!=`  
- `<`, `<=`  
- `>`, `>=`  

Used for filtering and conditional operations

In [10]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print("Equal:", a == b)        # [False, True, False]
print("Greater than:", a > b)  # [False, False, True]
print("Not equal:", a != b)    # [True, False, True]

# With broadcasting
matrix = np.arange(1,10).reshape(3,3)
print("\nMatrix > 5:\n", matrix > 5)
# [[False, False, False],
#  [False, False, True],
#  [True, True, True]]

# Combining conditions
condition = (matrix > 3) & (matrix < 7)
print("\n3 < Values < 7:\n", condition)

Equal: [False  True False]
Greater than: [False False  True]
Not equal: [ True False  True]

Matrix > 5:
 [[False False False]
 [False False  True]
 [ True  True  True]]

3 < Values < 7:
 [[False False False]
 [ True  True  True]
 [False False False]]


### Universal Functions (ufuncs)
Element-wise math functions:  
- `np.sin()`, `np.cos()`, `np.tan()`  
- `np.exp()`, `np.log()`  
- `np.sqrt()`, `np.abs()`  

Work with broadcasting

In [11]:
angles = np.array([0, np.pi/2, np.pi])
print("Sines:", np.sin(angles))  # [0,1,0]

values = np.array([1, 10, 100])
print("Log10:", np.log10(values))  # [0,1,2]

# Broadcasting with functions
matrix = np.array([[1,4], [9,16]])
print("\nSquare roots:\n", np.sqrt(matrix)) 
# [[1,2],
#  [3,4]]

Sines: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Log10: [0. 1. 2.]

Square roots:
 [[1. 2.]
 [3. 4.]]


### Aggregation Functions
Reduce arrays to summary statistics:  
- `np.sum()`, `np.prod()`  
- `np.mean()`, `np.median()`  
- `np.min()`, `np.max()`  
- `np.std()` (standard deviation)

In [4]:
import numpy as np
matrix = np.random.rand(3,4)
print(matrix)
print("Sum all:", np.sum(matrix))
print("Sum columns:", np.sum(matrix, axis=0))
print("Max rows:", np.max(matrix, axis=1))
print("Mean:", np.mean(matrix))
print("Std dev:", np.std(matrix))

# Combined with conditions
values = np.array([1, 2, 3, 4, 5])
print("\nMean of values >2:", np.mean(values[values>2]))

[[0.04450569 0.10816602 0.03196058 0.69635471]
 [0.59666411 0.31033453 0.22589877 0.23358772]
 [0.92740176 0.50714789 0.0063983  0.06754926]]
Sum all: 3.755969342302759
Sum columns: [1.56857155 0.92564845 0.26425765 0.99749169]
Max rows: [0.69635471 0.59666411 0.92740176]
Mean: 0.3129974451918966
Std dev: 0.2892215282545375

Mean of values >2: 4.0


### Real-World Use Cases
1. **Data normalization**: `(data - mean) / std`  
2. **Thresholding**: `image[image > 128] = 255`  
3. **Polynomial evaluation**: `x**3 + 2*x**2 + 5`  
4. **Distance matrices**: `np.sqrt(x**2 + y**2)`  

Try This: Create a temperature conversion function:

python
celsius = np.array([0, 100, 37])
fahrenheit = celsius * 9/5 + 32

In [37]:
import numpy as np 

def convertCelToFahr(celsius_array):
    return celsius_array * 9/5 + 32  

celsius = np.array([0, 100, 37])  

fahrenheit = convertCelToFahr(celsius)
print(fahrenheit)


[ 32.  212.   98.6]
