# Stacking & Splitting Arrays
- **Stacking**: Combine arrays along new/existing axis  
  `[1,2] + [3,4] → [[1,2], [3,4]]`  
- **Splitting**: Divide arrays into sub-arrays  

Primary methods:  
- Stacking: `np.hstack()`, `np.vstack()`, `np.concatenate()`  
- Splitting: `np.split()`, `np.array_split()`, `np.hsplit()`, `np.vsplit()`  

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 1D horizontal stack
h_stack = np.hstack((a, b))
print("1D hstack:", h_stack)  # [1,2,3,4,5,6]

# 2D horizontal stack
matrix_a = np.array([[1,2], [3,4]])
matrix_b = np.array([[5], [6]])
h_stack_2d = np.hstack((matrix_a, matrix_b))
print("\n2D hstack:\n", h_stack_2d)
# [[1,2,5],
#  [3,4,6]]

1D hstack: [1 2 3 4 5 6]

2D hstack:
 [[1 2 5]
 [3 4 6]]


In [2]:
# 1D vertical stack (creates 2D)
v_stack = np.vstack((a, b))
print("1D vstack:\n", v_stack)
# [[1,2,3],
#  [4,5,6]]

# 2D vertical stack
matrix_c = np.array([[7,8]])
v_stack_2d = np.vstack((matrix_a, matrix_c))
print("\n2D vstack:\n", v_stack_2d)
# [[1,2],
#  [3,4],
#  [7,8]]

1D vstack:
 [[1 2 3]
 [4 5 6]]

2D vstack:
 [[1 2]
 [3 4]
 [7 8]]


### `np.concatenate()` - Flexible Stacking
More general than `hstack`/`vstack`:  
```python
np.concatenate((a,b), axis=0)  # Vertical (default)  
np.concatenate((a,b), axis=1)  # Horizontal (2D+)  

### `np.concatenate()` - Flexible Stacking
More general than `hstack`/`vstack`:  
```python
np.concatenate((a,b), axis=0)  # Vertical (default)  
np.concatenate((a,b), axis=1)  # Horizontal (2D+)  

In [5]:

#### **Cell 5: Code - Concatenate Examples**

# 1D concatenation (axis=0 only)
cat_1d = np.concatenate((a, b))
print("1D concat:", cat_1d)  # [1,2,3,4,5,6]

# 2D vertical (axis=0)
v_cat = np.concatenate((matrix_a, matrix_c), axis=0)
print("\n2D vertical concat:\n", v_cat)

# 2D horizontal (axis=1)
h_cat = np.concatenate((matrix_a, matrix_b), axis=1)
print("\n2D horizontal concat:\n", h_cat)

# 3D concatenation
cube1 = np.ones((2,2,2))
cube2 = np.zeros((2,2,2))
cat_cube = np.concatenate((cube1, cube2), axis=2)
print("\n3D concat shape:", cat_cube.shape)  # (2,2,4)

1D concat: [1 2 3 4 5 6]

2D vertical concat:
 [[1 2]
 [3 4]
 [7 8]]

2D horizontal concat:
 [[1 2 5]
 [3 4 6]]

3D concat shape: (2, 2, 4)


## Array Splitting
Divide arrays into multiple sub-arrays:  
- `np.split()`: Equal splits only (error if unequal)  
- `np.array_split()`: Allows unequal splits  
- `np.hsplit()`/`np.vsplit()`: Axis-specific shortcuts  

In [6]:
arr = np.arange(10)  # [0,1,2,3,4,5,6,7,8,9]

# Equal splits (must divide evenly)
split_equal = np.split(arr, 2)
print("2 equal splits:", [a.tolist() for a in split_equal])  # [[0,1,2,3,4], [5,6,7,8,9]]

# Unequal splits (requires array_split)
split_unequal = np.array_split(arr, 4)
print("\n4 unequal splits:", [a.tolist() for a in split_unequal])
# [[0,1,2], [3,4,5], [6,7], [8,9]]

# 2D splitting
matrix = np.arange(1,10).reshape(3,3)
split_rows = np.array_split(matrix, 2, axis=0)
print("\nRow splitting:\n", split_rows[0], "\n", split_rows[1])
# [[1,2,3],
#  [4,5,6]] and [[7,8,9]]

2 equal splits: [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

4 unequal splits: [[0, 1, 2], [3, 4, 5], [6, 7], [8, 9]]

Row splitting:
 [[1 2 3]
 [4 5 6]] 
 [[7 8 9]]


In [7]:
# Horizontal splitting (columns)
matrix = np.array([[1,2,9], [3,4,8]])
h_split = np.hsplit(matrix, 3)  # Must divide evenly
print("hsplit results:")
for arr in h_split:
    print(arr)

# Vertical splitting (rows)
v_split = np.vsplit(matrix, 2)
print("\nvsplit results:")
for arr in v_split:
    print(arr)

# Split at specific indices
arr = np.arange(10)
custom_split = np.split(arr, [3, 7])  # Split at indices 3 and 7
print("\nCustom splits:", [a.tolist() for a in custom_split])  # [0:3], [3:7], [7:10]

hsplit results:
[[1]
 [3]]
[[2]
 [4]]
[[9]
 [8]]

vsplit results:
[[1 2 9]]
[[3 4 8]]

Custom splits: [[0, 1, 2], [3, 4, 5, 6], [7, 8, 9]]


### Real-World Use Cases
1. **Train/Test Splitting**:  
   `X_train, X_test = np.array_split(data, [800])`  
2. **Batch Processing**:  |
   Split large dataset into chunks  
3. **Feature/Label Separation**:  
   `features, labels = np.hsplit(dataset, [-1])`  
4. **Image Patch Extraction**:  
   Split image into tiles  

In [8]:
# 1. Train-test split
data = np.random.rand(1000, 5)
train, test = np.array_split(data, [800], axis=0)
print("Train shape:", train.shape)  # (800,5)
print("Test shape:", test.shape)    # (200,5)

# 2. Feature/label separation
dataset = np.hstack((data, np.random.rand(1000,1)))  # Add labels
features, labels = np.hsplit(dataset, [-1])  # Last column is label
print("\nFeatures shape:", features.shape)  # (1000,5)
print("Labels shape:", labels.shape)       # (1000,1)

# 3. Image tiling
image = np.random.rand(256, 256)
tiles = [np.hsplit(row, 8) for row in np.vsplit(image, 8)]
print("\nTile shape:", tiles[0][0].shape)  # (32,32)

Train shape: (800, 5)
Test shape: (200, 5)

Features shape: (1000, 5)
Labels shape: (1000, 1)

Tile shape: (32, 32)
