# NumPy Random Module
Key functions for random number generation:
1. **Uniform Distribution**: `np.random.rand()`  
2. **Normal Distribution**: `np.random.randn()`  
3. **Integers**: `np.random.randint()`  
4. **Sampling**: `np.random.choice()`  
5. **Reproducibility**: `np.random.seed()`  

Critical for:  
- Initializing ML weights  
- Data shuffling  
- Simulation modeling  

In [1]:
import numpy as np

# Generate 3 random floats in [0,1)
uniform_1d = np.random.rand(3)
print("1D uniform:", uniform_1d)

# 2x3 matrix of uniform randoms
uniform_2d = np.random.rand(2, 3)
print("\n2D uniform:\n", uniform_2d)

# Range conversion (0-100)
scaled = np.random.rand(5) * 100
print("\nScaled to 0-100:", scaled)

1D uniform: [0.38684507 0.17226788 0.33872512]

2D uniform:
 [[0.67161773 0.05470262 0.2275612 ]
 [0.93526367 0.05507154 0.58257347]]

Scaled to 0-100: [21.66421088 83.78572617  6.54785828  9.10725876 31.34976384]


In [2]:
# Standard normal (mean=0, std=1)
normal_1d = np.random.randn(3)
print("1D normal:", normal_1d)

# 2x2 matrix of normals
normal_2d = np.random.randn(2, 2)
print("\n2D normal:\n", normal_2d)

# Custom normal (mean=50, std=10)
custom_normal = np.random.randn(5) * 10 + 50
print("\nCustom normal (μ=50, σ=10):", custom_normal)

1D normal: [-2.69892258  1.07377965 -0.77978443]

2D normal:
 [[-0.69118433 -0.65842372]
 [-1.91446178  0.58211971]]

Custom normal (μ=50, σ=10): [41.36233613 45.50004562 41.93887878 52.0049723  50.98288485]


### `np.random.randint()`
Generates random integers in half-open interval `[low, high)`  
Parameters:  
- `low`: Inclusive lower bound  
- `high`: Exclusive upper bound  
- `size`: Output shape  

In [4]:
# Single integer between 0-9
rand_int = np.random.randint(10)
print("0-9 integer:", rand_int)

# Array of integers (1-100)
int_array = np.random.randint(1, 101, 5)
print("\n5 integers (1-100):", int_array)

# 3x3 matrix of integers
int_matrix = np.random.randint(-10, 11, (3,3))
print("\n3x3 integers (-10 to 10):\n", int_matrix)

0-9 integer: 3

5 integers (1-100): [35 87 50 71 92]

3x3 integers (-10 to 10):
 [[ 0 -7  1]
 [ 6 -2  5]
 [ 4 -8  0]]


In [5]:
# Single integer between 0-9
rand_int = np.random.randint(10)
print("0-9 integer:", rand_int)

# Array of integers (1-100)
int_array = np.random.randint(1, 101, 5)
print("\n5 integers (1-100):", int_array)

# 3x3 matrix of integers
int_matrix = np.random.randint(-10, 11, (3,3))
print("\n3x3 integers (-10 to 10):\n", int_matrix)

0-9 integer: 4

5 integers (1-100): [77 86 40 70 19]

3x3 integers (-10 to 10):
 [[  6  -6  -2]
 [ 10   9  -4]
 [  1  -4 -10]]


### `np.random.choice()`
Samples from given array with options:  
- `a`: Input array  
- `size`: Output shape  
- `replace`: With/without replacement  
- `p`: Probability distribution  

In [7]:
letters = ['A', 'B', 'C', 'D', 'E']

# Single random choice
single = np.random.choice(letters)
print("Single choice:", single)

# Multiple choices (with replacement)
multi = np.random.choice(letters, size=3)
print("\n3 choices (with replacement):", multi)

# Without replacement
unique = np.random.choice(letters, size=3, replace=False)
print("\n3 unique choices:", unique)

# Weighted probabilities
weighted = np.random.choice(letters, size=10, p=[0.5, 0.2, 0.1, 0.1, 0.1])
print("\nWeighted choices:", weighted)  # 'A' appears ~50% of time

Single choice: E

3 choices (with replacement): ['C' 'B' 'D']

3 unique choices: ['B' 'D' 'A']

Weighted choices: ['A' 'D' 'A' 'A' 'E' 'C' 'E' 'B' 'A' 'A']


## Setting Random Seed
Ensures reproducibility of random results:  
`np.random.seed(any_integer)`  

Critical for:  
- Debugging  
- Sharing reproducible research  
- Fair ML model comparisons  

In [8]:
# Without seed (different each run)
print("Unseeded random:", np.random.rand(3))

# With seed (reproducible)
np.random.seed(42)
first_run = np.random.rand(3)
print("\nSeeded first run:", first_run)

np.random.seed(42)  # Reset seed
second_run = np.random.rand(3)
print("Seeded second run:", second_run)  # Same as first_run

# Context manager for local seeding
with np.random.RandomState(123) as r:
    print("\nLocal seeded:", r.rand(3))

Unseeded random: [0.37619391 0.80529992 0.08250803]

Seeded first run: [0.37454012 0.95071431 0.73199394]
Seeded second run: [0.37454012 0.95071431 0.73199394]


TypeError: 'numpy.random.mtrand.RandomState' object does not support the context manager protocol

In [9]:
# Without seed (different each run)
print("Unseeded random:", np.random.rand(3))

# With seed (reproducible)
np.random.seed(42)
first_run = np.random.rand(3)
print("\nSeeded first run:", first_run)

np.random.seed(42)  # Reset seed
second_run = np.random.rand(3)
print("Seeded second run:", second_run)  # Same as first_run

# Context manager for local seeding
with np.random.RandomState(123) as r:
    print("\nLocal seeded:", r.rand(3))

Unseeded random: [0.59865848 0.15601864 0.15599452]

Seeded first run: [0.37454012 0.95071431 0.73199394]
Seeded second run: [0.37454012 0.95071431 0.73199394]


TypeError: 'numpy.random.mtrand.RandomState' object does not support the context manager protocol

### Additional Distributions
- **Binomial**: `np.random.binomial(n, p, size)`  
- **Poisson**: `np.random.poisson(lam, size)`  
- **Exponential**: `np.random.exponential(scale, size)`  
- **Shuffle**: `np.random.shuffle(arr)`  

In [10]:
# Binomial distribution (n=10 trials, p=0.5 success)
coin_flips = np.random.binomial(10, 0.5, 5)
print("Heads in 10 flips (5 samples):", coin_flips)

# Poisson distribution (λ=3 events)
website_visits = np.random.poisson(3, 10)
print("\nHourly website visits (λ=3):", website_visits)

# Shuffle array
arr = np.arange(10)
np.random.shuffle(arr)
print("\nShuffled array:", arr)

# Permutations
identity = np.arange(5)
permuted = np.random.permutation(identity)
print("Permutation:", permuted)

Heads in 10 flips (5 samples): [5 3 3 3 7]

Hourly website visits (λ=3): [2 3 2 3 2 3 0 2 4 2]

Shuffled array: [6 8 4 9 1 3 0 5 2 7]
Permutation: [2 0 4 3 1]


### Real-World Use Cases
1. **Train/Test Splitting**:  
   `indices = np.random.choice(len(data), test_size, replace=False)`  
2. **Weight Initialization**:  
   `weights = np.random.randn(input_dim, output_dim) * 0.01`  
3. **Data Augmentation**:  
   Random rotations/flips for images  
4. **Bootstrapping**:  
   `np.random.choice(data, size=len(data), replace=True)`  

In [11]:
# 1. Train-test split
data = np.arange(100)
test_indices = np.random.choice(100, 20, replace=False)
test_set = data[test_indices]
train_set = np.delete(data, test_indices)

# 2. Neural network initialization
def initialize_weights(dims):
    return np.random.randn(*dims) * 0.01

weights = initialize_weights((5, 3))
print("\nWeight matrix:\n", weights)

# 3. Data shuffling (before training)
features = np.random.rand(100, 5)
labels = np.random.randint(0, 2, 100)
shuffled_indices = np.random.permutation(len(features))
shuffled_X = features[shuffled_indices]
shuffled_y = labels[shuffled_indices]


Weight matrix:
 [[ 0.00257117  0.00314513  0.01371862]
 [ 0.00175553 -0.00309289  0.00673126]
 [-0.0025663  -0.00367826  0.01273734]
 [-0.00291953 -0.02655176  0.00345518]
 [-0.00395516 -0.00289137  0.00452936]]
