### 1. `np.array()` - Create Arrays from Sequences
Converts Python lists/tuples into NumPy arrays.  
**Key Notes**:
- Infers data type automatically
- Creates copies (not views) of the original data
- Supports multi-dimensional arrays

In [2]:
import numpy as np

# 1D array from list
list_1d = [1, 2, 3, 4]
arr_1d = np.array(list_1d)
print("1D Array:", arr_1d)

# 2D array from nested list
list_2d = [[1.1, 2.2], [3.3, 4.4]]
arr_2d = np.array(list_2d)
print("\n2D Array:\n", arr_2d)
print("Data type:", arr_2d.dtype)

# From tuple
tuple_data = (5, 6, 7)
arr_tuple = np.array(tuple_data)
print("\nFrom tuple:", arr_tuple)

1D Array: [1 2 3 4]

2D Array:
 [[1.1 2.2]
 [3.3 4.4]]
Data type: float64

From tuple: [5 6 7]


### 2. `np.zeros()`, `np.ones()`, `np.full()` - Prefilled Arrays
Create arrays with initial values:
- `zeros(shape)`: All 0s
- `ones(shape)`: All 1s
- `full(shape, value)`: Fill with any value

**Parameters**:
- `shape`: Tuple (rows, columns) for 2D, single number for 1D
- `dtype`: Optional data type (e.g., np.int32)

In [3]:
# 1D zeros
zeros_1d = np.zeros(5)
print("1D zeros:", zeros_1d)

# 2D ones (3x2 matrix)
ones_2d = np.ones((3, 2))
print("\n2D ones:\n", ones_2d)

# Full with custom value (4x4 filled with 7)
full_arr = np.full((4, 4), 7)
print("\nFull array (7s):\n", full_arr)

# With data type specification
int_zeros = np.zeros(3, dtype=np.int32)
print("\nInteger zeros:", int_zeros)

1D zeros: [0. 0. 0. 0. 0.]

2D ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (7s):
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Integer zeros: [0 0 0]


### 3. `np.arange()` & `np.linspace()` - Sequence Arrays
- **`arange(start, stop, step)`**: Like Python's range() but returns array  
  (Excludes stop value)
- **`linspace(start, stop, num)`**: Evenly spaced numbers over interval  
  (Includes stop value)

In [5]:
# arange (exclusive stop)
arr_arange = np.arange(0, 10, 2)  # 0 to 8, step 2
print("arange(0,10,2):", arr_arange)

# linspace (inclusive stop)
arr_lin = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print("\nlinspace(0,1,5):", arr_lin)

# Floating point step
arr_float = np.arange(0, 2.5, 0.5)
print("\nFloating step:", arr_float)

# 20 points between -π and π
angles = np.linspace(-np.pi, np.pi, 20)
print("\nAngles for trig:", angles[:5], "...")

arange(0,10,2): [0 2 4 6 8]

linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

Floating step: [0.  0.5 1.  1.5 2. ]

Angles for trig: [-3.14159265 -2.81089869 -2.48020473 -2.14951076 -1.8188168 ] ...


### 4. `np.eye()` - Identity Matrix
Creates square identity matrices (1s on diagonal, 0s elsewhere).  
**Parameters**:
- `N`: Matrix size (N x N)
- `k`: Diagonal offset (0=main diagonal)

In [6]:
# 3x3 identity matrix
eye3 = np.eye(3)
print("3x3 Identity:\n", eye3)

# 4x4 with offset diagonal
eye_offset = np.eye(4, k=1)  # Diagonal shifted up
print("\nOffset diagonal (k=1):\n", eye_offset)

# Non-square identity (5x3)
rect_eye = np.eye(5, 3)
print("\n5x3 'Identity':\n", rect_eye)

3x3 Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Offset diagonal (k=1):
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

5x3 'Identity':
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Summary Cheat Sheet
| Method                 | Use Case                          | Example                     |
|------------------------|-----------------------------------|-----------------------------|
| `np.array()`           | Convert existing sequences        | `np.array([[1,2],[3,4]])`   |
| `np.zeros()`           | Initialize with 0s                | `np.zeros((3,2))`           |
| `np.ones()`            | Initialize with 1s                | `np.ones(5)`                |
| `np.full()`            | Initialize with custom value      | `np.full((2,2), 7)`         |
| `np.arange()`          | Ranged sequences (exclusive stop) | `np.arange(0,10,2)`         |
| `np.linspace()`        | Evenly spaced (inclusive stop)    | `np.linspace(0,1,5)`        |
| `np.eye()`             | Identity matrices                 | `np.eye(3)`                 |

**Key Tip**: Use `?` in Jupyter to see docs (e.g., `np.arange?`)