## Array Attributes
Core properties of NumPy arrays:
1. `.shape` → Dimensions of the array (tuple)
2. `.ndim` → Number of dimensions (integer)
3. `.dtype` → Data type of elements
4. `.size` → Total number of elements

**Visualization**:

In [3]:

#### **Cell 2: Code (Setup)**

import numpy as np

# Create sample arrays
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
arr_3d = np.ones((2, 3, 4))  # 2 layers, 3 rows, 4 columns

### 1. `.shape` - Array Dimensions
Returns a tuple representing array dimensions:  
`(rows, columns)` for 2D, `(depth, rows, columns)` for 3D, etc.

[basics of reshape](http://youtube.com/watch?v=mMtKE_vpnD4)

[Reshape -1, 1 and Reshape 1, -1 in Python NumPy | Module NumPy Tutorial](https://www.youtube.com/watch?v=yDXNPyxDb0M)

In [19]:
print("1D shape:", arr_1d.shape)  # (5,)
print(arr_1d)
print("2D shape:", arr_2d.shape)  # (2, 3)
print("3D shape:", arr_3d.shape)  # (2, 3, 4)

# Practical use: Reshaping
reshaped = arr_1d.reshape((5, 1))  # Convert to 5x1 column vector
print("\nReshaped to column:\n", reshaped)
print("New shape:", reshaped.shape)

1D shape: (5,)
[1 2 3 4 5]
2D shape: (2, 3)
3D shape: (2, 3, 4)

Reshaped to column:
 [[1]
 [2]
 [3]
 [4]
 [5]]
New shape: (5, 1)


### 2. `.ndim` - Number of Dimensions
Returns an integer counting array dimensions:
- 1D → 1
- 2D → 2
- 3D → 3

In [5]:
print("1D ndim:", arr_1d.ndim)  # 1
print("2D ndim:", arr_2d.ndim)  # 2
print("3D ndim:", arr_3d.ndim)  # 3

# Scalar corner case
scalar = np.array(5)
print("\nScalar ndim:", scalar.ndim)  # 0

1D ndim: 1
2D ndim: 2
3D ndim: 3

Scalar ndim: 0


### 3. `.dtype` - Data Type
Returns the data type of array elements.  
**Common dtypes**:  
- `int32`, `int64` → Integers  
- `float32`, `float64` → Floats  
- `bool` → Boolean  
- `object` → Python objects  

In [6]:
print("1D dtype:", arr_1d.dtype)  # int64
print("2D dtype:", arr_2d.dtype)  # float64

# Control dtype during creation
int_arr = np.array([1.5, 2.7], dtype=np.int32)
print("\nFloat→Int conversion:", int_arr)  # [1, 2]
print("dtype:", int_arr.dtype)

# Check memory usage
print("\nFloat64 size:", np.array([1.0]).nbytes)  # 8 bytes
print("Float32 size:", np.array([1.0], dtype=np.float32).nbytes)  # 4 bytes

1D dtype: int64
2D dtype: float64

Float→Int conversion: [1 2]
dtype: int32

Float64 size: 8
Float32 size: 4


### 4. `.size` - Total Elements
Returns total number of elements in the array:  
`shape[0] * shape[1] * ... * shape[N]`

In [7]:
print("1D size:", arr_1d.size)  # 5
print("2D size:", arr_2d.size)  # 6 (2x3)
print("3D size:", arr_3d.size)  # 24 (2x3x4)

# Relationship with shape
print("\nVerify 2D: 2x3 =", arr_2d.shape[0] * arr_2d.shape[1])

1D size: 5
2D size: 6
3D size: 24

Verify 2D: 2x3 = 6


### Attribute Summary Table
| Attribute | Returns        | Example Output       | Use Case                     |
|-----------|----------------|----------------------|------------------------------|
| `.shape`  | Tuple          | (2, 3)              | Reshaping, broadcasting      |
| `.ndim`   | Integer        | 2                   | Loop depth decisions         |
| `.dtype`  | Data type      | float64             | Memory optimization          |
| `.size`   | Integer        | 6                   | Allocation/preallocation     |

**Tip**: Use `arr.nbytes` for total memory consumption.

In [9]:
def summarize_array(arr, name):
    print(f"\n{name} Summary:")
    print("Shape: ", arr.shape)
    print("ndim:  ", arr.ndim)
    print("dtype: ", arr.dtype)
    print("size:  ", arr.size)
    print("nbytes:", arr.nbytes, "bytes")

summarize_array(arr_2d, "2D Array")
summarize_array(np.array([True, False]), "Boolean Array")


2D Array Summary:
Shape:  (2, 3)
ndim:   2
dtype:  float64
size:   6
nbytes: 48 bytes

Boolean Array Summary:
Shape:  (2,)
ndim:   1
dtype:  bool
size:   2
nbytes: 2 bytes


In [14]:
import numpy as np

# Create a 3D array with shape (2, 3, 4)
# This means:
# - 2 "layers" (or 2D arrays)
# - 3 rows per layer
# - 4 columns per layer
data = np.array([
    [  # First "layer" (index 0)
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [  # Second "layer" (index 1)
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

print("The full 3D array:\n", data)
print("\nShape of the array:", data.shape)

The full 3D array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Shape of the array: (2, 3, 4)


[NumPy 3d Array Creation Tutorial](https://www.youtube.com/watch?v=SjtXNJy9RCk)

## `astype()` - Data Type Conversion
Converts array to new data type while creating a **copy** (original unchanged).  

**Key Points**:  
- Always returns new array  
- Supports all NumPy dtypes (`int32`, `float64`, `bool`, etc.)  
- Handles truncation/rounding when converting between types  
- Critical for memory optimization and precision control  

### Syntax
`new_array = old_array.astype(dtype, copy=True)`

**Parameters**:
- `dtype`: Target data type (e.g., `np.float32`)
- `copy`: Default `True` (always copy). Set `False` to avoid copy *if possible*

In [16]:
import numpy as np

# Float → Integer (truncates decimals)
floats = np.array([1.7, 2.2, 3.5])
ints = floats.astype(np.int32)
print("Float to int:", ints)  # [1, 2, 3]

# Integer → Float
integers = np.array([1, 2, 3])
new_floats = integers.astype(np.float64)
print("\nInt to float:", new_floats)  # [1., 2., 3.]

# Boolean conversion
data = np.array([0, 1, -1, 0])
bools = data.astype(bool)
print("\nNumeric to bool:", bools)  # [False, True, True, False]

Float to int: [1 2 3]

Int to float: [1. 2. 3.]

Numeric to bool: [False  True  True False]


### Common Use Cases
1. **Precision Control**:  
   `images.astype(np.float32)` for ML models  
2. **Memory Optimization**:  
   `big_data.astype(np.int16)` for large datasets  
3. **Type Requirements**:  
   `array.astype(int)` for scikit-learn input  
4. **Boolean Masking**:  
   `(array > 0).astype(int)` for 0/1 encoding  