# Indexing & Slicing in NumPy
Key concepts:
1. **Indexing**: Access single elements
2. **Slicing**: Access subarrays
3. **Boolean Indexing**: Filter with conditions
4. **Fancy Indexing**: Access non-contiguous elements

**Zero-based indexing** applies across all dimensions

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access single elements
print("First element:", arr[0])     # 10
print("Last element:", arr[-1])     # 50

# Modify elements
arr[1] = 99
print("Modified array:", arr)       # [10, 99, 30, 40, 50]

First element: 10
Last element: 50
Modified array: [10 99 30 40 50]


### 1D Slicing Syntax
`arr[start:stop:step]`  
- `start`: Inclusive (default 0)  
- `stop`: Exclusive (default end)  
- `step`: Interval (default 1)  

In [15]:
arr = np.arange(10)  # [0,1,2,3,4,5,6,7,8,9]

# Basic slices
print("First 3:", arr[:3])        # [0,1,2]
print("Last 3:", arr[-3:])       # [7,8,9]
print("Every 2nd:", arr[::2])    # [0,2,4,6,8]
print("Reverse:", arr[::-1])     # [9,8,7,6,5,4,3,2,1,0]
print("Middle:", arr[3:7])       # [3,4,5,6]

# Slice assignment
arr[2:5] = 99
print("Assigned slice:", arr)    # [0,1,99,99,99,5,6,7,8,9]

First 3: [0 1 2]
Last 3: [7 8 9]
Every 2nd: [0 2 4 6 8]
Reverse: [9 8 7 6 5 4 3 2 1 0]
Middle: [3 4 5 6]
Assigned slice: [ 0  1 99 99 99  5  6  7  8  9]


## 2D Arrays (Matrix Indexing)
Syntax: `arr[row_index, col_index]`  
Can use:
- Integers for specific positions
- Slices for ranges
- `:` for entire dimension

In [18]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Single element
print("Top-left:", matrix[0, 0])    # 1
print("Bottom-right:", matrix[2, 2]) # 9

# Full row/column
print("\nMiddle row:", matrix[1, :])   # [4,5,6]
print("Last column:", matrix[:, -1])  # [3,6,9]

# Submatrix
print("\nTop-left 2x2:\n", matrix[:2, :2])
# [[1,2],
#  [4,5]]

# Step slicing
print("\nEvery other row:\n", matrix[::2, :])
# [[1,2,3],
#  [7,8,9]]

Top-left: 1
Bottom-right: 9

Middle row: [4 5 6]
Last column: [3 6 9]

Top-left 2x2:
 [[1 2]
 [4 5]]

Every other row:
 [[1 2 3]
 [7 8 9]]


## Boolean Indexing
Filter elements using conditions.  
Returns a view of elements where condition is True.

In [9]:
arr = np.array([5, 10, 15, 20, 25])

# Simple condition
print(">15:", arr[arr > 15])  # [20,25]

# Multiple conditions
condition = (arr % 10 == 0) | (arr < 8)
print("Div by 10 OR <8:", arr[condition])  # [5,10,20]

# 2D example
matrix = np.random.randint(0, 10, (3,3))
print("\nMatrix:\n", matrix)
print("Values >5:\n", matrix[matrix > 5])

>15: [20 25]
Div by 10 OR <8: [ 5 10 20]

Matrix:
 [[7 0 6]
 [9 1 5]
 [9 1 8]]
Values >5:
 [7 6 9 9 8]


## Fancy Indexing (Integer Array Indexing)
Access non-adjacent elements using index arrays.  
Returns a copy, not a view.

In [16]:
arr = np.array([10, 20, 30, 40, 50])

# 1D fancy indexing
indices = [0, 2, 4]
print("Selected indices:", arr[indices])  # [10,30,50]
print(arr) #the original array is same not changed 

# 2D fancy indexing
matrix = np.array([[1,2], [3,4], [5,6]])
row_indices = [0, 2]
col_indices = [1, 0]
print("\nSelected elements:", matrix[row_indices, col_indices])  # [2,5]

# Combined with slices
print("\nFirst and last rows:\n", matrix[[0, -1], :])
# [[1,2],
#  [5,6]]

Selected indices: [10 30 50]
[10 20 30 40 50]

Selected elements: [2 5]

First and last rows:
 [[1 2]
 [5 6]]


## Critical Distinction: Views vs Copies
- **Slices**: Return views (modify original)
- **Fancy/Boolean Indexing**: Return copies (safe to modify)
- **Use `arr.base` to check if view**

In [11]:
arr = np.arange(10)

# Slice (view)
slice_view = arr[2:5]
slice_view[0] = 99
print("Original modified:", arr)  # [0,1,99,3,4,5,6,7,8,9]

# Fancy indexing (copy)
indices = [1,3,5]
fancy_copy = arr[indices]
fancy_copy[0] = 100
print("\nOriginal unchanged:", arr)  # Still has 99 at index2

# Check if view
print("\nIs slice a view?", slice_view.base is arr)  # True
print("Is fancy a view?", fancy_copy.base is arr)   # False

Original modified: [ 0  1 99  3  4  5  6  7  8  9]

Original unchanged: [ 0  1 99  3  4  5  6  7  8  9]

Is slice a view? True
Is fancy a view? False


### Pro Tips
1. Use `.copy()` to explicitly create copies
2. Combine indexing methods: `matrix[rows, :][:, cols]`
3. Ellipsis (`...`) for higher dimensions: `arr[..., 0]`
4. `np.where()` for conditional logic

In [13]:
chess = np.zeros((8,8))
chess[::2, ::2] = 1
chess[1::2, 1::2] = 1

print(chess)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
